### ISSUE TITLE
Question on Value.__mul__

### ISSUE THREAD

**Issue by lukasnxyz** [x0axz/ngrad#1]
In the `__mul__` function on line 50 of `ngrad/engine.py` defining `out`, should the multiplication not be `np.matmul` instead of just `*`? Am also trying to build something out like karpathy's/your library and am stuck on this.

**Comment by x0axz** [comment]
The use of `*` for multiplication is appropriate in this context. The implementation follows element-wise multiplication for the `Value` instances, aligning with typical usage in mathematical expressions involving arrays or tensors. Utilizing `np.matmul` would be suitable for matrix multiplication, which is not the case here.
